version: '2'
services:
  zookeeper:
    image: 
    ports:
      - "2181:2181"
  
  kafka:
    image: 

    environment:
      # kafak가 클라이언트에게 이 주소로 접속해줘라고 알리는 정보
      # 각 서비스의 통신방식을 지정(암호화지정 여부)
      # kafak가 실제 통신해서 듣고 있는 주소 정보 
      # zookeeper 클러스터와 연결 
      # kafka server - client 사용할 리스너정보 


