# cloud ver. 

# eureka server는 사용하지 않음 bc 클라우드 환경에서는 eureka의 역할을 aws의 pod가 대신함 
eureka:
  client:
    enabled: false

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
        # cores 처리
        # 각 서비스 모듈은 웹브라우저와 직접 통신하지 않으므로 단일 진입점인 gateway 담당
        globalcors:
            cors-configurations:
                '[/**]':
                    allowedOrigins:
                        - 'http://localhost:3000' # react(frontend) s3Bucket의 end-point
                    allowedMethods: '*'
                    allowedHeaders: '*'
                    exposedHeaders: '*'
                    allowCredentials: true

        # eureka server 에 등록된 client 찾아서 사용자의 url_pattern을 매핑하는 작업 
        routes:
            - id: user-service
              predicates: 
                - Path=/user-service/**
              filters:
                # 첫번째 접두어를 제거하라는 의미 
                # browser : http://server.xxxxx.shop/user-service/users/signIn
                # inner   : http://server.xxxxx.shop/users/signIn
                - StripPrefix=1 
              uri: http://user-service

            - id: product-service
              predicates: 
                - Path=/product-service/**
              filters:
                # 첫번째 접두어를 제거하라는 의미 
                # browser : http://server.xxxxx.shop/product-service/product/create
                # inner   : http://server.xxxxx.shop/product/signIn
                - StripPrefix=1 
              uri: http://product-service

            - id: order-service
              predicates: 
                - Path=/order-service/**
              filters:
                # 첫번째 접두어를 제거하라는 의미 
                # browser : http://server.xxxxx.shop/product-service/product/create
                # inner   : http://server.xxxxx.shop/product/signIn
                - StripPrefix=1 
              uri: http://order-service
                
jwt:
  secret: wlguss-jihyun-springsecurity-key-test-forjwtprovider-134679


