name: deploy order

# main 브렌치의 코드 변경이 감지되면 아래 pipeline 동작 (trigger)
on:
  push:
    branches:
      - main

jobs:
  # job name
  build-and-deploy:
    # runner (OS 설치 작업)
    runs-on: ubuntu-latest

    steps:
      - name: checkout github
        uses: actions/checkout@v2 
